[workspace]
authors = ["JoelStansbury <stansbury.joel@gmail.com>"]
channels = ["conda-forge"]
name = "json-pouch"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
setup = "npm install"
code = "code ."
tsc = "npx tsc"
main = "node src/javascript/index.js"
test = "npx jest"
[dependencies]
nodejs = "*"

