[workspace]
authors = ["JoelStansbury <stansbury.joel@gmail.com>"]
channels = ["conda-forge"]
name = "json-pouch"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks.setup]
cmd = "npm install"
inputs = ['package.json']
outputs = ['package-lock.json']

[tasks.test]
cmd = "npx jest"
depends-on = ["setup"]

[tasks.fix]
cmd = "npx eslint --fix src"
depends-on = ["setup"]

[tasks.code]
cmd = "code ."
depends-on = ["setup"]

[dependencies]
nodejs = "*"

